[package]
name = "saikyo-no-benkyoho"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
hyper = "1.6.0"
sqlx = { version = "0.8.3", features = [
  "runtime-tokio",
  "tls-rustls-ring",
  "postgres",
  "time",
  "uuid",
] }
tokio = { version = "1", features = ["full"] }
